-- Create terminal_assignments table
CREATE TABLE terminal_assignments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    terminal_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    assigned_by VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_terminal_assignments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_terminal_assignments_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(id) ON DELETE CASCADE,
    CONSTRAINT fk_terminal_assignments_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    
    -- Unique constraint to prevent duplicate assignments
    CONSTRAINT uk_terminal_assignments_user_terminal UNIQUE (user_id, terminal_id)
);

-- Add indexes for better performance
CREATE INDEX idx_terminal_assignments_user ON terminal_assignments(user_id);
CREATE INDEX idx_terminal_assignments_terminal ON terminal_assignments(terminal_id);
CREATE INDEX idx_terminal_assignments_store ON terminal_assignments(store_id);
CREATE INDEX idx_terminal_assignments_active ON terminal_assignments(active);
CREATE INDEX idx_terminal_assignments_expires_at ON terminal_assignments(expires_at);

-- Add comments
COMMENT ON TABLE terminal_assignments IS 'Stores user-terminal assignments for authorization management';
COMMENT ON COLUMN terminal_assignments.user_id IS 'Reference to the user assigned to the terminal';
COMMENT ON COLUMN terminal_assignments.terminal_id IS 'Reference to the terminal assigned to the user';
COMMENT ON COLUMN terminal_assignments.store_id IS 'Reference to the store where the assignment is valid';
COMMENT ON COLUMN terminal_assignments.active IS 'Whether the assignment is currently active';
COMMENT ON COLUMN terminal_assignments.assigned_at IS 'When the assignment was created';
COMMENT ON COLUMN terminal_assignments.expires_at IS 'When the assignment expires (nullable for permanent assignments)';
COMMENT ON COLUMN terminal_assignments.assigned_by IS 'Username of who created this assignment';
COMMENT ON COLUMN terminal_assignments.notes IS 'Additional notes about the assignment';

COMMENT ON COLUMN terminals.type IS 'Type of terminal (CASH_REGISTER, KIOSK, MOBILE_POS, etc.)'; 